ruRU_gossip_texts = {
	["ezekiel said that you might have a certain book..."] = "Иезекииль говорит что у тебя есть кой какая книга...",
	["get out of here, tobias, you're free!"] = "Вы свободны, Тобиас! Уходите!",
	["i am ready to begin."] = "Я "..ST_G("готов", "готова")..".",
	["i am ready, as are my forces. let us end this masquerade!"] = "Я "..ST_G("готов", "готова")..". Давайте положим конец этому маскараду!",
	["i am ready, oronok. let us destroy cyrukh and free the elements!"] = "Я "..ST_G("готов", "готова")..", Оронок. Давайте уничтожим Цируха и освободим элементалей!",
	["i cannot, vaelastrasz! surely something can be done to heal you!"] = "Не могу, Валестраз! Ведь есть же какой-то способ тебя вылечить!",
	["i need a moment of your time, sir."] = "Мне нужна минута вашего времени, сэр.",
	["i've made no mistakes."] = "Я не "..ST_G("сделал", "сделала").." ни одной ошибки.",
	["let marshal windsor know that i am ready."] = "Дай знать маршалу Виндзору что я "..ST_G("готов", "готова")..".",
	["let the event begin!"] = "Идем.",
	["let's find out."] = "Давай разберемся.",
	["let's see what you have."] = "Давай посмотрим, что у тебя есть.",
	["please do."] = "Давай.",
	["please unlock the courtyard door."] = "Открой дверь во внутренний двор.",
	["tell me more."] = "Продолжай.",
	["turn the key to start the machine."] = "Повернуть ключ, чтобы запустить машину.",
	["vaelastrasz, no!!!"] = "Валестраз, нет!!!",
	["what else do you have to say?"] = "Что еще вы хотели сказать?",
	["why don't you and rocknot go find somewhere private..."] = "Почему бы вам с Камнеузлом не пойти и найти какое-нибудь укромное место...",
	["why... yes, of course. i've something to show you right inside this building, mr. anvilward."] = "Почему... да, конечно. Я "..ST_G("хотел", "хотела").." бы что-то показать внутри этого здания, мистер Наковальня.",
	["you challenged us and we have come. where is this master you speak of?"] = "Ты бросил нам вызов, и мы пришли. Где тот господин, о котором ты говорил?",
	["you have lost your mind, nefarius. you speak in riddles."] = "Ты совсем свихнулся, Нефарий. Ты разговариваешь загадками.",
	["you're free, dughal! get out of here!"] = "Вы свободны, Дугал! Уходите!",
	["your bondage is at an end, doom'rel. i challenge you!"] = "Кончилось твое заточение, Рок’рел. Вызываю тебя на бой!",
	["[ph] sd2 unknown text"] = "[PH] SD2 неизвестный текст",
}

